### ISSUE TITLE
doesn't work reliably

### ISSUE THREAD

**Issue by dany-on-demand** [evilworks/nppsync#2]
latest chrome, it works sporadically, is there a timeout or something it's annoying

it always works the first time, ctrl+shift+alt+r and hit the red thing and it updates. never again after

**Comment by duzun** [comment]
You could try this repo: https://github.com/duzun/nppsync

I don't pretend it's perfect, but it has more features.

Maybe it works for you

**Comment by dany-on-demand** [comment]
hmmkay let's c-ee

edit:
k that satisfies my needs
